PD = playdate
GFX = PD.graphics
SLIB = GFX.sprite

CRANK_SPEED = 6
TOTAL_LEVELS = 1
TEST_LEVEL = 7
DEFAULT_PLAYER_DIRECTION = 'down'
DEFAULT_LASER_CADENCE = 2
DEFAULT_LASER_OFFSET = 0
DEFAULT_GUARD_DIRECTION = 'down'
DEFAULT_MOUSE_DIRECTION = 'down'

TILE_SIZE = 20
TILES_PER_ROW  = 20
TILES_PER_COLUMN = 12
TILE_SPRITE_OFFSET = 9

DIRECTIONS = {UP = 'up', DOWN = 'down', LEFT = 'left', RIGHT = 'right'}
EMPTY_TILE  = 0
WALL_TILE = 1
RIGHT_LASER_TILE = 2
LEFT_LASER_TILE = 3
UP_LASER_TILE = 4
DOWN_LASER_TILE = 5
GUARD_TILE = 6
MOUSE_TILE = 7
LADDER_TILE = 8
PLAYER_TILE = 9
