PD = playdate
GFX = PD.graphics
SLIB = GFX.sprite

CRANK_SPEED = 6
TOTAL_LEVELS = 3

TILE_SIZE = 20
TILES_PER_ROW  = 20
TILES_PER_COLUMN = 12
TILE_SPRITE_OFFSET = 9

DIRECTIONS = {UP = 'up', DOWN = 'down', LEFT = 'left', RIGHT = 'right'}
EMPTY_TILE  = 0
WALL_TILE = 1
RIGHT_LASER_TILE = 2
LEFT_LASER_TILE = 3
UP_LASER_TILE = 4
DOWN_LASER_TILE = 5
LADDER_TILE = 8
PLAYER_TILE = 9
