PD = playdate
GFX = PD.graphics
SLIB = GFX.sprite

DIRECTIONS = {UP = -1, DOWN = 1, LEFT = -2, RIGHT = 2}
CRANK_SPEED = 6
TOTAL_LEVELS = 1
TEST_LEVEL = 7
DEFAULT_PLAYER_DIRECTION = DIRECTIONS.DOWN
DEFAULT_LASER_CADENCE = 2
DEFAULT_LASER_OFFSET = 0
DEFAULT_GUARD_DIRECTION = DIRECTIONS.DOWN
DEFAULT_MOUSE_DIRECTION = DIRECTIONS.DOWN
DEFAULT_MOUSE_DELAY = 2

TILE_SIZE = 20
TILES_PER_ROW  = 20
TILES_PER_COLUMN = 12
TILE_SPRITE_OFFSET = 9

EMPTY_TILE  = 0
WALL_TILE = 1
RIGHT_LASER_TILE = 2
LEFT_LASER_TILE = 3
UP_LASER_TILE = 4
DOWN_LASER_TILE = 5
GUARD_TILE = 6
MOUSE_TILE = 7
LADDER_TILE = 8
PLAYER_TILE = 9
